from __future__ import annotations

from typing import Literal

NationBuilderResource = Literal[
    "async_processes",
    "automation_enrollments",
    "automations",
    "ballots",
    "broadcasters",
    "contacts",
    "custom_fields",
    "donation_tracking_codes",
    "donations",
    "elections",
    "event_rsvps",
    "event_ticket_levels",
    "events",
    "imports",
    "lists",
    "mailings",
    "membership_types",
    "memberships",
    "pages",
    "path_histories",
    "path_journey_status_changes",
    "path_journeys",
    "path_steps",
    "paths",
    "petition_signatures",
    "petitions",
    "pledges",
    "precincts",
    "relationships",
    "signup_profiles",
    "signup_taggings",
    "signup_tags",
    "signups",
    "sites",
    "survey_question_possible_responses",
    "survey_question_responses",
    "survey_questions",
    "surveys",
    "voters",
]

NOT_IMPLEMENTED: set[str] = {"async_processes"}

PUSH_SIGNUPS_REQUIRED_KEYS: set[str] = {
    "civicrm_id",
    "county_file_id",
    "datatrust_id",
    "dw_id",
    "email",
    "external_id",
    "mobile_number",
    "ngp_id",
    "pf_strat_id",
    "phone_number",
    "rnc_id",
    "rnc_regid",
    "salesforce_id",
    "state_file_id",
    "van_id",
    "work_phone_number",
}